export const LOGIN_SET_USER = 'LOGIN_SET_USER';
export const LOGIN_SET_ERROR = 'LOGIN_SET_ERROR';
export const LOGIN_SET_ISLOADING = 'LOGIN_SET_ISLOADING';
export const LOGIN_SET_VIOLATIONS = 'LOGIN_SET_VIOLATIONS';
export const LOGIN_SET_CREATED = 'LOGIN_SET_CREATED';
export const LOGIN_SET_INDEX_ROUTE = 'LOGIN_SET_INDEX_ROUTE';
export const SIGN_UP_FIELDS = 'SIGN_UP_FIELDS';
export const SIGN_UP_CUSTOM_BG = 'SIGN_UP_CUSTOM_BG';
